// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Match struct {
	ID            int32              `json:"id"`
	HomeTeamID    int32              `json:"home_team_id"`
	AwayTeamID    int32              `json:"away_team_id"`
	MatchDate     pgtype.Timestamptz `json:"match_date"`
	Competition   string             `json:"competition"`
	Season        string             `json:"season"`
	Round         *string            `json:"round"`
	Stadium       *string            `json:"stadium"`
	Attendance    *int32             `json:"attendance"`
	Status        string             `json:"status"`
	Referee       *string            `json:"referee"`
	HomeTeamScore int32              `json:"home_team_score"`
	AwayTeamScore int32              `json:"away_team_score"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type MatchEvent struct {
	ID                int32              `json:"id"`
	MatchID           int32              `json:"match_id"`
	TeamID            *int32             `json:"team_id"`
	PlayerID          *int32             `json:"player_id"`
	SecondaryPlayerID *int32             `json:"secondary_player_id"`
	EventType         string             `json:"event_type"`
	Minute            int32              `json:"minute"`
	ExtraMinute       *int32             `json:"extra_minute"`
	PositionX         pgtype.Numeric     `json:"position_x"`
	PositionY         pgtype.Numeric     `json:"position_y"`
	Description       *string            `json:"description"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type Player struct {
	ID            int32              `json:"id"`
	TeamID        int32              `json:"team_id"`
	FirstName     string             `json:"first_name"`
	LastName      string             `json:"last_name"`
	FullName      string             `json:"full_name"`
	DateOfBirth   pgtype.Date        `json:"date_of_birth"`
	Nationality   *string            `json:"nationality"`
	Position      string             `json:"position"`
	ShirtNumber   *int32             `json:"shirt_number"`
	Height        *int32             `json:"height"`
	Weight        *int32             `json:"weight"`
	PreferredFoot *string            `json:"preferred_foot"`
	Photo         *string            `json:"photo"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type PlayerStatistic struct {
	ID              int32              `json:"id"`
	PlayerID        int32              `json:"player_id"`
	Season          string             `json:"season"`
	Competition     string             `json:"competition"`
	MatchesPlayed   int32              `json:"matches_played"`
	MatchesStarted  int32              `json:"matches_started"`
	MinutesPlayed   int32              `json:"minutes_played"`
	SubOn           int32              `json:"sub_on"`
	SubOff          int32              `json:"sub_off"`
	Goals           int32              `json:"goals"`
	Assists         int32              `json:"assists"`
	ShotsTotal      int32              `json:"shots_total"`
	ShotsOnTarget   int32              `json:"shots_on_target"`
	ShotAccuracy    pgtype.Numeric     `json:"shot_accuracy"`
	GoalConversion  pgtype.Numeric     `json:"goal_conversion"`
	PassesTotal     int32              `json:"passes_total"`
	PassesCompleted int32              `json:"passes_completed"`
	PassAccuracy    pgtype.Numeric     `json:"pass_accuracy"`
	KeyPasses       int32              `json:"key_passes"`
	Crosses         int32              `json:"crosses"`
	Tackles         int32              `json:"tackles"`
	TacklesWon      int32              `json:"tackles_won"`
	Interceptions   int32              `json:"interceptions"`
	Clearances      int32              `json:"clearances"`
	BlockedShots    int32              `json:"blocked_shots"`
	Duels           int32              `json:"duels"`
	DuelsWon        int32              `json:"duels_won"`
	AerialDuels     int32              `json:"aerial_duels"`
	AerialDuelsWon  int32              `json:"aerial_duels_won"`
	YellowCards     int32              `json:"yellow_cards"`
	RedCards        int32              `json:"red_cards"`
	Fouls           int32              `json:"fouls"`
	FoulsDrawn      int32              `json:"fouls_drawn"`
	CleanSheets     *int32             `json:"clean_sheets"`
	GoalsConceded   *int32             `json:"goals_conceded"`
	SavesTotal      *int32             `json:"saves_total"`
	SavePercentage  pgtype.Numeric     `json:"save_percentage"`
	PenaltiesSaved  *int32             `json:"penalties_saved"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type Team struct {
	ID              int32              `json:"id"`
	Name            string             `json:"name"`
	ShortName       string             `json:"short_name"`
	Code            string             `json:"code"`
	Country         string             `json:"country"`
	City            *string            `json:"city"`
	Stadium         *string            `json:"stadium"`
	StadiumCapacity *int32             `json:"stadium_capacity"`
	Founded         *int32             `json:"founded"`
	Logo            *string            `json:"logo"`
	Colors          *string            `json:"colors"`
	Website         *string            `json:"website"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type TeamStatistic struct {
	ID                      int32              `json:"id"`
	TeamID                  int32              `json:"team_id"`
	Season                  string             `json:"season"`
	Competition             string             `json:"competition"`
	MatchesPlayed           int32              `json:"matches_played"`
	Wins                    int32              `json:"wins"`
	Draws                   int32              `json:"draws"`
	Losses                  int32              `json:"losses"`
	Points                  int32              `json:"points"`
	Position                *int32             `json:"position"`
	GoalsScored             int32              `json:"goals_scored"`
	GoalsConceded           int32              `json:"goals_conceded"`
	GoalDifference          int32              `json:"goal_difference"`
	CleanSheets             int32              `json:"clean_sheets"`
	GoalsPerMatch           pgtype.Numeric     `json:"goals_per_match"`
	HomeWins                int32              `json:"home_wins"`
	HomeDraws               int32              `json:"home_draws"`
	HomeLosses              int32              `json:"home_losses"`
	AwayWins                int32              `json:"away_wins"`
	AwayDraws               int32              `json:"away_draws"`
	AwayLosses              int32              `json:"away_losses"`
	Possession              pgtype.Numeric     `json:"possession"`
	PassAccuracy            pgtype.Numeric     `json:"pass_accuracy"`
	ShotsPerMatch           pgtype.Numeric     `json:"shots_per_match"`
	ShotsOnTargetPercentage pgtype.Numeric     `json:"shots_on_target_percentage"`
	YellowCards             int32              `json:"yellow_cards"`
	RedCards                int32              `json:"red_cards"`
	CurrentForm             *string            `json:"current_form"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID            int32              `json:"id"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	FirstName     string             `json:"first_name"`
	LastName      string             `json:"last_name"`
	Role          string             `json:"role"`
	Avatar        *string            `json:"avatar"`
	Organization  *string            `json:"organization"`
	IsActive      bool               `json:"is_active"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}
