// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountEventsByType(ctx context.Context, arg CountEventsByTypeParams) (int64, error)
	CountMatchEvents(ctx context.Context, matchID int32) (int64, error)
	CountMatches(ctx context.Context) (int64, error)
	CountMatchesByTeam(ctx context.Context, homeTeamID int32) (int64, error)
	CountPlayers(ctx context.Context) (int64, error)
	CountPlayersByTeam(ctx context.Context, teamID int32) (int64, error)
	CountTeams(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error)
	CreateMatchEvent(ctx context.Context, arg CreateMatchEventParams) (MatchEvent, error)
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	CreatePlayerStats(ctx context.Context, arg CreatePlayerStatsParams) (PlayerStatistic, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateTeamStats(ctx context.Context, arg CreateTeamStatsParams) (TeamStatistic, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMatch(ctx context.Context, id int32) error
	DeleteMatchEvent(ctx context.Context, id int32) error
	DeletePlayer(ctx context.Context, id int32) error
	DeletePlayerStats(ctx context.Context, id int32) error
	DeleteTeam(ctx context.Context, id int32) error
	DeleteTeamStats(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetCardsByMatch(ctx context.Context, matchID int32) ([]MatchEvent, error)
	GetGoalsByMatch(ctx context.Context, matchID int32) ([]MatchEvent, error)
	GetLeagueTable(ctx context.Context, arg GetLeagueTableParams) ([]GetLeagueTableRow, error)
	GetLiveMatches(ctx context.Context) ([]Match, error)
	GetMatchByID(ctx context.Context, id int32) (Match, error)
	GetMatchEventByID(ctx context.Context, id int32) (MatchEvent, error)
	GetMatchEvents(ctx context.Context, matchID int32) ([]MatchEvent, error)
	GetMatchEventsByType(ctx context.Context, arg GetMatchEventsByTypeParams) ([]MatchEvent, error)
	GetMatchWithTeams(ctx context.Context, id int32) (GetMatchWithTeamsRow, error)
	GetMatchesByCompetition(ctx context.Context, arg GetMatchesByCompetitionParams) ([]Match, error)
	GetMatchesByCompetitionAndSeason(ctx context.Context, arg GetMatchesByCompetitionAndSeasonParams) ([]Match, error)
	GetMatchesBySeason(ctx context.Context, arg GetMatchesBySeasonParams) ([]Match, error)
	GetMatchesByStatus(ctx context.Context, arg GetMatchesByStatusParams) ([]Match, error)
	GetMatchesByTeam(ctx context.Context, arg GetMatchesByTeamParams) ([]Match, error)
	GetPassesByMatch(ctx context.Context, matchID int32) ([]MatchEvent, error)
	GetPlayerByID(ctx context.Context, id int32) (Player, error)
	GetPlayerEvents(ctx context.Context, arg GetPlayerEventsParams) ([]MatchEvent, error)
	GetPlayerPassAccuracy(ctx context.Context, playerID *int32) (GetPlayerPassAccuracyRow, error)
	// Analytics queries for match events
	GetPlayerShotsWithXG(ctx context.Context, arg GetPlayerShotsWithXGParams) ([]GetPlayerShotsWithXGRow, error)
	// Player Statistics Queries
	GetPlayerStatsByID(ctx context.Context, id int32) (PlayerStatistic, error)
	GetPlayerStatsByPlayer(ctx context.Context, playerID int32) ([]PlayerStatistic, error)
	GetPlayerStatsByPlayerAndSeason(ctx context.Context, arg GetPlayerStatsByPlayerAndSeasonParams) (PlayerStatistic, error)
	GetPlayerWithTeam(ctx context.Context, id int32) (GetPlayerWithTeamRow, error)
	GetPlayersByPosition(ctx context.Context, arg GetPlayersByPositionParams) ([]Player, error)
	GetPlayersByTeam(ctx context.Context, teamID int32) ([]Player, error)
	GetShotsByMatch(ctx context.Context, matchID int32) ([]MatchEvent, error)
	GetTeamByCode(ctx context.Context, code string) (Team, error)
	GetTeamByID(ctx context.Context, id int32) (Team, error)
	GetTeamEventsInMatch(ctx context.Context, arg GetTeamEventsInMatchParams) ([]MatchEvent, error)
	GetTeamPossessionEvents(ctx context.Context, matchID int32) ([]GetTeamPossessionEventsRow, error)
	// Team Statistics Queries
	GetTeamStatsByID(ctx context.Context, id int32) (TeamStatistic, error)
	GetTeamStatsByTeam(ctx context.Context, teamID int32) ([]TeamStatistic, error)
	GetTeamStatsByTeamAndSeason(ctx context.Context, arg GetTeamStatsByTeamAndSeasonParams) (TeamStatistic, error)
	GetTeamsByCountry(ctx context.Context, country string) ([]Team, error)
	GetTopAssisters(ctx context.Context, arg GetTopAssistersParams) ([]GetTopAssistersRow, error)
	GetTopScorers(ctx context.Context, arg GetTopScorersParams) ([]GetTopScorersRow, error)
	GetUpcomingMatches(ctx context.Context, limit int32) ([]Match, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	ListMatches(ctx context.Context, arg ListMatchesParams) ([]Match, error)
	ListPlayers(ctx context.Context, arg ListPlayersParams) ([]Player, error)
	ListTeams(ctx context.Context, arg ListTeamsParams) ([]Team, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	SearchPlayersByName(ctx context.Context, arg SearchPlayersByNameParams) ([]Player, error)
	SearchTeamsByName(ctx context.Context, arg SearchTeamsByNameParams) ([]Team, error)
	UpdateMatch(ctx context.Context, arg UpdateMatchParams) (Match, error)
	UpdateMatchEvent(ctx context.Context, arg UpdateMatchEventParams) (MatchEvent, error)
	UpdateMatchScore(ctx context.Context, arg UpdateMatchScoreParams) (Match, error)
	UpdateMatchStatus(ctx context.Context, arg UpdateMatchStatusParams) (Match, error)
	UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (Player, error)
	UpdatePlayerStats(ctx context.Context, arg UpdatePlayerStatsParams) (PlayerStatistic, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
	UpdateTeamStats(ctx context.Context, arg UpdateTeamStatsParams) (TeamStatistic, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
}

var _ Querier = (*Queries)(nil)
