// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: statistics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlayerStats = `-- name: CreatePlayerStats :one
INSERT INTO player_statistics (
    player_id, season, competition, matches_played, matches_started, minutes_played,
    sub_on, sub_off, goals, assists, shots_total, shots_on_target, shot_accuracy,
    goal_conversion, passes_total, passes_completed, pass_accuracy, key_passes, crosses,
    tackles, tackles_won, interceptions, clearances, blocked_shots, duels, duels_won,
    aerial_duels, aerial_duels_won, yellow_cards, red_cards, fouls, fouls_drawn,
    clean_sheets, goals_conceded, saves_total, save_percentage, penalties_saved
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19,
    $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37
)
RETURNING id, player_id, season, competition, matches_played, matches_started, minutes_played, sub_on, sub_off, goals, assists, shots_total, shots_on_target, shot_accuracy, goal_conversion, passes_total, passes_completed, pass_accuracy, key_passes, crosses, tackles, tackles_won, interceptions, clearances, blocked_shots, duels, duels_won, aerial_duels, aerial_duels_won, yellow_cards, red_cards, fouls, fouls_drawn, clean_sheets, goals_conceded, saves_total, save_percentage, penalties_saved, created_at, updated_at, deleted_at
`

type CreatePlayerStatsParams struct {
	PlayerID        int32          `json:"player_id"`
	Season          string         `json:"season"`
	Competition     string         `json:"competition"`
	MatchesPlayed   int32          `json:"matches_played"`
	MatchesStarted  int32          `json:"matches_started"`
	MinutesPlayed   int32          `json:"minutes_played"`
	SubOn           int32          `json:"sub_on"`
	SubOff          int32          `json:"sub_off"`
	Goals           int32          `json:"goals"`
	Assists         int32          `json:"assists"`
	ShotsTotal      int32          `json:"shots_total"`
	ShotsOnTarget   int32          `json:"shots_on_target"`
	ShotAccuracy    pgtype.Numeric `json:"shot_accuracy"`
	GoalConversion  pgtype.Numeric `json:"goal_conversion"`
	PassesTotal     int32          `json:"passes_total"`
	PassesCompleted int32          `json:"passes_completed"`
	PassAccuracy    pgtype.Numeric `json:"pass_accuracy"`
	KeyPasses       int32          `json:"key_passes"`
	Crosses         int32          `json:"crosses"`
	Tackles         int32          `json:"tackles"`
	TacklesWon      int32          `json:"tackles_won"`
	Interceptions   int32          `json:"interceptions"`
	Clearances      int32          `json:"clearances"`
	BlockedShots    int32          `json:"blocked_shots"`
	Duels           int32          `json:"duels"`
	DuelsWon        int32          `json:"duels_won"`
	AerialDuels     int32          `json:"aerial_duels"`
	AerialDuelsWon  int32          `json:"aerial_duels_won"`
	YellowCards     int32          `json:"yellow_cards"`
	RedCards        int32          `json:"red_cards"`
	Fouls           int32          `json:"fouls"`
	FoulsDrawn      int32          `json:"fouls_drawn"`
	CleanSheets     *int32         `json:"clean_sheets"`
	GoalsConceded   *int32         `json:"goals_conceded"`
	SavesTotal      *int32         `json:"saves_total"`
	SavePercentage  pgtype.Numeric `json:"save_percentage"`
	PenaltiesSaved  *int32         `json:"penalties_saved"`
}

func (q *Queries) CreatePlayerStats(ctx context.Context, arg CreatePlayerStatsParams) (PlayerStatistic, error) {
	row := q.db.QueryRow(ctx, createPlayerStats,
		arg.PlayerID,
		arg.Season,
		arg.Competition,
		arg.MatchesPlayed,
		arg.MatchesStarted,
		arg.MinutesPlayed,
		arg.SubOn,
		arg.SubOff,
		arg.Goals,
		arg.Assists,
		arg.ShotsTotal,
		arg.ShotsOnTarget,
		arg.ShotAccuracy,
		arg.GoalConversion,
		arg.PassesTotal,
		arg.PassesCompleted,
		arg.PassAccuracy,
		arg.KeyPasses,
		arg.Crosses,
		arg.Tackles,
		arg.TacklesWon,
		arg.Interceptions,
		arg.Clearances,
		arg.BlockedShots,
		arg.Duels,
		arg.DuelsWon,
		arg.AerialDuels,
		arg.AerialDuelsWon,
		arg.YellowCards,
		arg.RedCards,
		arg.Fouls,
		arg.FoulsDrawn,
		arg.CleanSheets,
		arg.GoalsConceded,
		arg.SavesTotal,
		arg.SavePercentage,
		arg.PenaltiesSaved,
	)
	var i PlayerStatistic
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Season,
		&i.Competition,
		&i.MatchesPlayed,
		&i.MatchesStarted,
		&i.MinutesPlayed,
		&i.SubOn,
		&i.SubOff,
		&i.Goals,
		&i.Assists,
		&i.ShotsTotal,
		&i.ShotsOnTarget,
		&i.ShotAccuracy,
		&i.GoalConversion,
		&i.PassesTotal,
		&i.PassesCompleted,
		&i.PassAccuracy,
		&i.KeyPasses,
		&i.Crosses,
		&i.Tackles,
		&i.TacklesWon,
		&i.Interceptions,
		&i.Clearances,
		&i.BlockedShots,
		&i.Duels,
		&i.DuelsWon,
		&i.AerialDuels,
		&i.AerialDuelsWon,
		&i.YellowCards,
		&i.RedCards,
		&i.Fouls,
		&i.FoulsDrawn,
		&i.CleanSheets,
		&i.GoalsConceded,
		&i.SavesTotal,
		&i.SavePercentage,
		&i.PenaltiesSaved,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTeamStats = `-- name: CreateTeamStats :one
INSERT INTO team_statistics (
    team_id, season, competition, matches_played, wins, draws, losses, points, position,
    goals_scored, goals_conceded, goal_difference, clean_sheets, goals_per_match,
    home_wins, home_draws, home_losses, away_wins, away_draws, away_losses,
    possession, pass_accuracy, shots_per_match, shots_on_target_percentage,
    yellow_cards, red_cards, current_form
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19,
    $20, $21, $22, $23, $24, $25, $26, $27
)
RETURNING id, team_id, season, competition, matches_played, wins, draws, losses, points, position, goals_scored, goals_conceded, goal_difference, clean_sheets, goals_per_match, home_wins, home_draws, home_losses, away_wins, away_draws, away_losses, possession, pass_accuracy, shots_per_match, shots_on_target_percentage, yellow_cards, red_cards, current_form, created_at, updated_at, deleted_at
`

type CreateTeamStatsParams struct {
	TeamID                  int32          `json:"team_id"`
	Season                  string         `json:"season"`
	Competition             string         `json:"competition"`
	MatchesPlayed           int32          `json:"matches_played"`
	Wins                    int32          `json:"wins"`
	Draws                   int32          `json:"draws"`
	Losses                  int32          `json:"losses"`
	Points                  int32          `json:"points"`
	Position                *int32         `json:"position"`
	GoalsScored             int32          `json:"goals_scored"`
	GoalsConceded           int32          `json:"goals_conceded"`
	GoalDifference          int32          `json:"goal_difference"`
	CleanSheets             int32          `json:"clean_sheets"`
	GoalsPerMatch           pgtype.Numeric `json:"goals_per_match"`
	HomeWins                int32          `json:"home_wins"`
	HomeDraws               int32          `json:"home_draws"`
	HomeLosses              int32          `json:"home_losses"`
	AwayWins                int32          `json:"away_wins"`
	AwayDraws               int32          `json:"away_draws"`
	AwayLosses              int32          `json:"away_losses"`
	Possession              pgtype.Numeric `json:"possession"`
	PassAccuracy            pgtype.Numeric `json:"pass_accuracy"`
	ShotsPerMatch           pgtype.Numeric `json:"shots_per_match"`
	ShotsOnTargetPercentage pgtype.Numeric `json:"shots_on_target_percentage"`
	YellowCards             int32          `json:"yellow_cards"`
	RedCards                int32          `json:"red_cards"`
	CurrentForm             *string        `json:"current_form"`
}

func (q *Queries) CreateTeamStats(ctx context.Context, arg CreateTeamStatsParams) (TeamStatistic, error) {
	row := q.db.QueryRow(ctx, createTeamStats,
		arg.TeamID,
		arg.Season,
		arg.Competition,
		arg.MatchesPlayed,
		arg.Wins,
		arg.Draws,
		arg.Losses,
		arg.Points,
		arg.Position,
		arg.GoalsScored,
		arg.GoalsConceded,
		arg.GoalDifference,
		arg.CleanSheets,
		arg.GoalsPerMatch,
		arg.HomeWins,
		arg.HomeDraws,
		arg.HomeLosses,
		arg.AwayWins,
		arg.AwayDraws,
		arg.AwayLosses,
		arg.Possession,
		arg.PassAccuracy,
		arg.ShotsPerMatch,
		arg.ShotsOnTargetPercentage,
		arg.YellowCards,
		arg.RedCards,
		arg.CurrentForm,
	)
	var i TeamStatistic
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Season,
		&i.Competition,
		&i.MatchesPlayed,
		&i.Wins,
		&i.Draws,
		&i.Losses,
		&i.Points,
		&i.Position,
		&i.GoalsScored,
		&i.GoalsConceded,
		&i.GoalDifference,
		&i.CleanSheets,
		&i.GoalsPerMatch,
		&i.HomeWins,
		&i.HomeDraws,
		&i.HomeLosses,
		&i.AwayWins,
		&i.AwayDraws,
		&i.AwayLosses,
		&i.Possession,
		&i.PassAccuracy,
		&i.ShotsPerMatch,
		&i.ShotsOnTargetPercentage,
		&i.YellowCards,
		&i.RedCards,
		&i.CurrentForm,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePlayerStats = `-- name: DeletePlayerStats :exec
UPDATE player_statistics
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeletePlayerStats(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePlayerStats, id)
	return err
}

const deleteTeamStats = `-- name: DeleteTeamStats :exec
UPDATE team_statistics
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteTeamStats(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTeamStats, id)
	return err
}

const getLeagueTable = `-- name: GetLeagueTable :many
SELECT
    ts.id, ts.team_id, ts.season, ts.competition, ts.matches_played, ts.wins, ts.draws, ts.losses, ts.points, ts.position, ts.goals_scored, ts.goals_conceded, ts.goal_difference, ts.clean_sheets, ts.goals_per_match, ts.home_wins, ts.home_draws, ts.home_losses, ts.away_wins, ts.away_draws, ts.away_losses, ts.possession, ts.pass_accuracy, ts.shots_per_match, ts.shots_on_target_percentage, ts.yellow_cards, ts.red_cards, ts.current_form, ts.created_at, ts.updated_at, ts.deleted_at,
    t.name,
    t.short_name,
    t.code,
    t.logo
FROM team_statistics ts
JOIN teams t ON ts.team_id = t.id AND t.deleted_at IS NULL
WHERE ts.season = $1
  AND ts.competition = $2
  AND ts.deleted_at IS NULL
ORDER BY ts.points DESC, ts.goal_difference DESC, ts.goals_scored DESC
`

type GetLeagueTableParams struct {
	Season      string `json:"season"`
	Competition string `json:"competition"`
}

type GetLeagueTableRow struct {
	ID                      int32              `json:"id"`
	TeamID                  int32              `json:"team_id"`
	Season                  string             `json:"season"`
	Competition             string             `json:"competition"`
	MatchesPlayed           int32              `json:"matches_played"`
	Wins                    int32              `json:"wins"`
	Draws                   int32              `json:"draws"`
	Losses                  int32              `json:"losses"`
	Points                  int32              `json:"points"`
	Position                *int32             `json:"position"`
	GoalsScored             int32              `json:"goals_scored"`
	GoalsConceded           int32              `json:"goals_conceded"`
	GoalDifference          int32              `json:"goal_difference"`
	CleanSheets             int32              `json:"clean_sheets"`
	GoalsPerMatch           pgtype.Numeric     `json:"goals_per_match"`
	HomeWins                int32              `json:"home_wins"`
	HomeDraws               int32              `json:"home_draws"`
	HomeLosses              int32              `json:"home_losses"`
	AwayWins                int32              `json:"away_wins"`
	AwayDraws               int32              `json:"away_draws"`
	AwayLosses              int32              `json:"away_losses"`
	Possession              pgtype.Numeric     `json:"possession"`
	PassAccuracy            pgtype.Numeric     `json:"pass_accuracy"`
	ShotsPerMatch           pgtype.Numeric     `json:"shots_per_match"`
	ShotsOnTargetPercentage pgtype.Numeric     `json:"shots_on_target_percentage"`
	YellowCards             int32              `json:"yellow_cards"`
	RedCards                int32              `json:"red_cards"`
	CurrentForm             *string            `json:"current_form"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
	Name                    string             `json:"name"`
	ShortName               string             `json:"short_name"`
	Code                    string             `json:"code"`
	Logo                    *string            `json:"logo"`
}

func (q *Queries) GetLeagueTable(ctx context.Context, arg GetLeagueTableParams) ([]GetLeagueTableRow, error) {
	rows, err := q.db.Query(ctx, getLeagueTable, arg.Season, arg.Competition)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLeagueTableRow{}
	for rows.Next() {
		var i GetLeagueTableRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Season,
			&i.Competition,
			&i.MatchesPlayed,
			&i.Wins,
			&i.Draws,
			&i.Losses,
			&i.Points,
			&i.Position,
			&i.GoalsScored,
			&i.GoalsConceded,
			&i.GoalDifference,
			&i.CleanSheets,
			&i.GoalsPerMatch,
			&i.HomeWins,
			&i.HomeDraws,
			&i.HomeLosses,
			&i.AwayWins,
			&i.AwayDraws,
			&i.AwayLosses,
			&i.Possession,
			&i.PassAccuracy,
			&i.ShotsPerMatch,
			&i.ShotsOnTargetPercentage,
			&i.YellowCards,
			&i.RedCards,
			&i.CurrentForm,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.ShortName,
			&i.Code,
			&i.Logo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerStatsByID = `-- name: GetPlayerStatsByID :one

SELECT id, player_id, season, competition, matches_played, matches_started, minutes_played, sub_on, sub_off, goals, assists, shots_total, shots_on_target, shot_accuracy, goal_conversion, passes_total, passes_completed, pass_accuracy, key_passes, crosses, tackles, tackles_won, interceptions, clearances, blocked_shots, duels, duels_won, aerial_duels, aerial_duels_won, yellow_cards, red_cards, fouls, fouls_drawn, clean_sheets, goals_conceded, saves_total, save_percentage, penalties_saved, created_at, updated_at, deleted_at FROM player_statistics
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

// Player Statistics Queries
func (q *Queries) GetPlayerStatsByID(ctx context.Context, id int32) (PlayerStatistic, error) {
	row := q.db.QueryRow(ctx, getPlayerStatsByID, id)
	var i PlayerStatistic
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Season,
		&i.Competition,
		&i.MatchesPlayed,
		&i.MatchesStarted,
		&i.MinutesPlayed,
		&i.SubOn,
		&i.SubOff,
		&i.Goals,
		&i.Assists,
		&i.ShotsTotal,
		&i.ShotsOnTarget,
		&i.ShotAccuracy,
		&i.GoalConversion,
		&i.PassesTotal,
		&i.PassesCompleted,
		&i.PassAccuracy,
		&i.KeyPasses,
		&i.Crosses,
		&i.Tackles,
		&i.TacklesWon,
		&i.Interceptions,
		&i.Clearances,
		&i.BlockedShots,
		&i.Duels,
		&i.DuelsWon,
		&i.AerialDuels,
		&i.AerialDuelsWon,
		&i.YellowCards,
		&i.RedCards,
		&i.Fouls,
		&i.FoulsDrawn,
		&i.CleanSheets,
		&i.GoalsConceded,
		&i.SavesTotal,
		&i.SavePercentage,
		&i.PenaltiesSaved,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPlayerStatsByPlayer = `-- name: GetPlayerStatsByPlayer :many
SELECT id, player_id, season, competition, matches_played, matches_started, minutes_played, sub_on, sub_off, goals, assists, shots_total, shots_on_target, shot_accuracy, goal_conversion, passes_total, passes_completed, pass_accuracy, key_passes, crosses, tackles, tackles_won, interceptions, clearances, blocked_shots, duels, duels_won, aerial_duels, aerial_duels_won, yellow_cards, red_cards, fouls, fouls_drawn, clean_sheets, goals_conceded, saves_total, save_percentage, penalties_saved, created_at, updated_at, deleted_at FROM player_statistics
WHERE player_id = $1 AND deleted_at IS NULL
ORDER BY season DESC, competition
`

func (q *Queries) GetPlayerStatsByPlayer(ctx context.Context, playerID int32) ([]PlayerStatistic, error) {
	rows, err := q.db.Query(ctx, getPlayerStatsByPlayer, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayerStatistic{}
	for rows.Next() {
		var i PlayerStatistic
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Season,
			&i.Competition,
			&i.MatchesPlayed,
			&i.MatchesStarted,
			&i.MinutesPlayed,
			&i.SubOn,
			&i.SubOff,
			&i.Goals,
			&i.Assists,
			&i.ShotsTotal,
			&i.ShotsOnTarget,
			&i.ShotAccuracy,
			&i.GoalConversion,
			&i.PassesTotal,
			&i.PassesCompleted,
			&i.PassAccuracy,
			&i.KeyPasses,
			&i.Crosses,
			&i.Tackles,
			&i.TacklesWon,
			&i.Interceptions,
			&i.Clearances,
			&i.BlockedShots,
			&i.Duels,
			&i.DuelsWon,
			&i.AerialDuels,
			&i.AerialDuelsWon,
			&i.YellowCards,
			&i.RedCards,
			&i.Fouls,
			&i.FoulsDrawn,
			&i.CleanSheets,
			&i.GoalsConceded,
			&i.SavesTotal,
			&i.SavePercentage,
			&i.PenaltiesSaved,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerStatsByPlayerAndSeason = `-- name: GetPlayerStatsByPlayerAndSeason :one
SELECT id, player_id, season, competition, matches_played, matches_started, minutes_played, sub_on, sub_off, goals, assists, shots_total, shots_on_target, shot_accuracy, goal_conversion, passes_total, passes_completed, pass_accuracy, key_passes, crosses, tackles, tackles_won, interceptions, clearances, blocked_shots, duels, duels_won, aerial_duels, aerial_duels_won, yellow_cards, red_cards, fouls, fouls_drawn, clean_sheets, goals_conceded, saves_total, save_percentage, penalties_saved, created_at, updated_at, deleted_at FROM player_statistics
WHERE player_id = $1 AND season = $2 AND competition = $3 AND deleted_at IS NULL
LIMIT 1
`

type GetPlayerStatsByPlayerAndSeasonParams struct {
	PlayerID    int32  `json:"player_id"`
	Season      string `json:"season"`
	Competition string `json:"competition"`
}

func (q *Queries) GetPlayerStatsByPlayerAndSeason(ctx context.Context, arg GetPlayerStatsByPlayerAndSeasonParams) (PlayerStatistic, error) {
	row := q.db.QueryRow(ctx, getPlayerStatsByPlayerAndSeason, arg.PlayerID, arg.Season, arg.Competition)
	var i PlayerStatistic
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Season,
		&i.Competition,
		&i.MatchesPlayed,
		&i.MatchesStarted,
		&i.MinutesPlayed,
		&i.SubOn,
		&i.SubOff,
		&i.Goals,
		&i.Assists,
		&i.ShotsTotal,
		&i.ShotsOnTarget,
		&i.ShotAccuracy,
		&i.GoalConversion,
		&i.PassesTotal,
		&i.PassesCompleted,
		&i.PassAccuracy,
		&i.KeyPasses,
		&i.Crosses,
		&i.Tackles,
		&i.TacklesWon,
		&i.Interceptions,
		&i.Clearances,
		&i.BlockedShots,
		&i.Duels,
		&i.DuelsWon,
		&i.AerialDuels,
		&i.AerialDuelsWon,
		&i.YellowCards,
		&i.RedCards,
		&i.Fouls,
		&i.FoulsDrawn,
		&i.CleanSheets,
		&i.GoalsConceded,
		&i.SavesTotal,
		&i.SavePercentage,
		&i.PenaltiesSaved,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTeamStatsByID = `-- name: GetTeamStatsByID :one

SELECT id, team_id, season, competition, matches_played, wins, draws, losses, points, position, goals_scored, goals_conceded, goal_difference, clean_sheets, goals_per_match, home_wins, home_draws, home_losses, away_wins, away_draws, away_losses, possession, pass_accuracy, shots_per_match, shots_on_target_percentage, yellow_cards, red_cards, current_form, created_at, updated_at, deleted_at FROM team_statistics
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

// Team Statistics Queries
func (q *Queries) GetTeamStatsByID(ctx context.Context, id int32) (TeamStatistic, error) {
	row := q.db.QueryRow(ctx, getTeamStatsByID, id)
	var i TeamStatistic
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Season,
		&i.Competition,
		&i.MatchesPlayed,
		&i.Wins,
		&i.Draws,
		&i.Losses,
		&i.Points,
		&i.Position,
		&i.GoalsScored,
		&i.GoalsConceded,
		&i.GoalDifference,
		&i.CleanSheets,
		&i.GoalsPerMatch,
		&i.HomeWins,
		&i.HomeDraws,
		&i.HomeLosses,
		&i.AwayWins,
		&i.AwayDraws,
		&i.AwayLosses,
		&i.Possession,
		&i.PassAccuracy,
		&i.ShotsPerMatch,
		&i.ShotsOnTargetPercentage,
		&i.YellowCards,
		&i.RedCards,
		&i.CurrentForm,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTeamStatsByTeam = `-- name: GetTeamStatsByTeam :many
SELECT id, team_id, season, competition, matches_played, wins, draws, losses, points, position, goals_scored, goals_conceded, goal_difference, clean_sheets, goals_per_match, home_wins, home_draws, home_losses, away_wins, away_draws, away_losses, possession, pass_accuracy, shots_per_match, shots_on_target_percentage, yellow_cards, red_cards, current_form, created_at, updated_at, deleted_at FROM team_statistics
WHERE team_id = $1 AND deleted_at IS NULL
ORDER BY season DESC, competition
`

func (q *Queries) GetTeamStatsByTeam(ctx context.Context, teamID int32) ([]TeamStatistic, error) {
	rows, err := q.db.Query(ctx, getTeamStatsByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamStatistic{}
	for rows.Next() {
		var i TeamStatistic
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Season,
			&i.Competition,
			&i.MatchesPlayed,
			&i.Wins,
			&i.Draws,
			&i.Losses,
			&i.Points,
			&i.Position,
			&i.GoalsScored,
			&i.GoalsConceded,
			&i.GoalDifference,
			&i.CleanSheets,
			&i.GoalsPerMatch,
			&i.HomeWins,
			&i.HomeDraws,
			&i.HomeLosses,
			&i.AwayWins,
			&i.AwayDraws,
			&i.AwayLosses,
			&i.Possession,
			&i.PassAccuracy,
			&i.ShotsPerMatch,
			&i.ShotsOnTargetPercentage,
			&i.YellowCards,
			&i.RedCards,
			&i.CurrentForm,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamStatsByTeamAndSeason = `-- name: GetTeamStatsByTeamAndSeason :one
SELECT id, team_id, season, competition, matches_played, wins, draws, losses, points, position, goals_scored, goals_conceded, goal_difference, clean_sheets, goals_per_match, home_wins, home_draws, home_losses, away_wins, away_draws, away_losses, possession, pass_accuracy, shots_per_match, shots_on_target_percentage, yellow_cards, red_cards, current_form, created_at, updated_at, deleted_at FROM team_statistics
WHERE team_id = $1 AND season = $2 AND competition = $3 AND deleted_at IS NULL
LIMIT 1
`

type GetTeamStatsByTeamAndSeasonParams struct {
	TeamID      int32  `json:"team_id"`
	Season      string `json:"season"`
	Competition string `json:"competition"`
}

func (q *Queries) GetTeamStatsByTeamAndSeason(ctx context.Context, arg GetTeamStatsByTeamAndSeasonParams) (TeamStatistic, error) {
	row := q.db.QueryRow(ctx, getTeamStatsByTeamAndSeason, arg.TeamID, arg.Season, arg.Competition)
	var i TeamStatistic
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Season,
		&i.Competition,
		&i.MatchesPlayed,
		&i.Wins,
		&i.Draws,
		&i.Losses,
		&i.Points,
		&i.Position,
		&i.GoalsScored,
		&i.GoalsConceded,
		&i.GoalDifference,
		&i.CleanSheets,
		&i.GoalsPerMatch,
		&i.HomeWins,
		&i.HomeDraws,
		&i.HomeLosses,
		&i.AwayWins,
		&i.AwayDraws,
		&i.AwayLosses,
		&i.Possession,
		&i.PassAccuracy,
		&i.ShotsPerMatch,
		&i.ShotsOnTargetPercentage,
		&i.YellowCards,
		&i.RedCards,
		&i.CurrentForm,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTopAssisters = `-- name: GetTopAssisters :many
SELECT
    ps.id, ps.player_id, ps.season, ps.competition, ps.matches_played, ps.matches_started, ps.minutes_played, ps.sub_on, ps.sub_off, ps.goals, ps.assists, ps.shots_total, ps.shots_on_target, ps.shot_accuracy, ps.goal_conversion, ps.passes_total, ps.passes_completed, ps.pass_accuracy, ps.key_passes, ps.crosses, ps.tackles, ps.tackles_won, ps.interceptions, ps.clearances, ps.blocked_shots, ps.duels, ps.duels_won, ps.aerial_duels, ps.aerial_duels_won, ps.yellow_cards, ps.red_cards, ps.fouls, ps.fouls_drawn, ps.clean_sheets, ps.goals_conceded, ps.saves_total, ps.save_percentage, ps.penalties_saved, ps.created_at, ps.updated_at, ps.deleted_at,
    p.full_name,
    p.position,
    t.name as team_name
FROM player_statistics ps
JOIN players p ON ps.player_id = p.id AND p.deleted_at IS NULL
JOIN teams t ON p.team_id = t.id AND t.deleted_at IS NULL
WHERE ps.season = $1
  AND ps.competition = $2
  AND ps.deleted_at IS NULL
ORDER BY ps.assists DESC, ps.goals DESC
LIMIT $3
`

type GetTopAssistersParams struct {
	Season      string `json:"season"`
	Competition string `json:"competition"`
	Limit       int32  `json:"limit"`
}

type GetTopAssistersRow struct {
	ID              int32              `json:"id"`
	PlayerID        int32              `json:"player_id"`
	Season          string             `json:"season"`
	Competition     string             `json:"competition"`
	MatchesPlayed   int32              `json:"matches_played"`
	MatchesStarted  int32              `json:"matches_started"`
	MinutesPlayed   int32              `json:"minutes_played"`
	SubOn           int32              `json:"sub_on"`
	SubOff          int32              `json:"sub_off"`
	Goals           int32              `json:"goals"`
	Assists         int32              `json:"assists"`
	ShotsTotal      int32              `json:"shots_total"`
	ShotsOnTarget   int32              `json:"shots_on_target"`
	ShotAccuracy    pgtype.Numeric     `json:"shot_accuracy"`
	GoalConversion  pgtype.Numeric     `json:"goal_conversion"`
	PassesTotal     int32              `json:"passes_total"`
	PassesCompleted int32              `json:"passes_completed"`
	PassAccuracy    pgtype.Numeric     `json:"pass_accuracy"`
	KeyPasses       int32              `json:"key_passes"`
	Crosses         int32              `json:"crosses"`
	Tackles         int32              `json:"tackles"`
	TacklesWon      int32              `json:"tackles_won"`
	Interceptions   int32              `json:"interceptions"`
	Clearances      int32              `json:"clearances"`
	BlockedShots    int32              `json:"blocked_shots"`
	Duels           int32              `json:"duels"`
	DuelsWon        int32              `json:"duels_won"`
	AerialDuels     int32              `json:"aerial_duels"`
	AerialDuelsWon  int32              `json:"aerial_duels_won"`
	YellowCards     int32              `json:"yellow_cards"`
	RedCards        int32              `json:"red_cards"`
	Fouls           int32              `json:"fouls"`
	FoulsDrawn      int32              `json:"fouls_drawn"`
	CleanSheets     *int32             `json:"clean_sheets"`
	GoalsConceded   *int32             `json:"goals_conceded"`
	SavesTotal      *int32             `json:"saves_total"`
	SavePercentage  pgtype.Numeric     `json:"save_percentage"`
	PenaltiesSaved  *int32             `json:"penalties_saved"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	FullName        string             `json:"full_name"`
	Position        string             `json:"position"`
	TeamName        string             `json:"team_name"`
}

func (q *Queries) GetTopAssisters(ctx context.Context, arg GetTopAssistersParams) ([]GetTopAssistersRow, error) {
	rows, err := q.db.Query(ctx, getTopAssisters, arg.Season, arg.Competition, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopAssistersRow{}
	for rows.Next() {
		var i GetTopAssistersRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Season,
			&i.Competition,
			&i.MatchesPlayed,
			&i.MatchesStarted,
			&i.MinutesPlayed,
			&i.SubOn,
			&i.SubOff,
			&i.Goals,
			&i.Assists,
			&i.ShotsTotal,
			&i.ShotsOnTarget,
			&i.ShotAccuracy,
			&i.GoalConversion,
			&i.PassesTotal,
			&i.PassesCompleted,
			&i.PassAccuracy,
			&i.KeyPasses,
			&i.Crosses,
			&i.Tackles,
			&i.TacklesWon,
			&i.Interceptions,
			&i.Clearances,
			&i.BlockedShots,
			&i.Duels,
			&i.DuelsWon,
			&i.AerialDuels,
			&i.AerialDuelsWon,
			&i.YellowCards,
			&i.RedCards,
			&i.Fouls,
			&i.FoulsDrawn,
			&i.CleanSheets,
			&i.GoalsConceded,
			&i.SavesTotal,
			&i.SavePercentage,
			&i.PenaltiesSaved,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FullName,
			&i.Position,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopScorers = `-- name: GetTopScorers :many
SELECT
    ps.id, ps.player_id, ps.season, ps.competition, ps.matches_played, ps.matches_started, ps.minutes_played, ps.sub_on, ps.sub_off, ps.goals, ps.assists, ps.shots_total, ps.shots_on_target, ps.shot_accuracy, ps.goal_conversion, ps.passes_total, ps.passes_completed, ps.pass_accuracy, ps.key_passes, ps.crosses, ps.tackles, ps.tackles_won, ps.interceptions, ps.clearances, ps.blocked_shots, ps.duels, ps.duels_won, ps.aerial_duels, ps.aerial_duels_won, ps.yellow_cards, ps.red_cards, ps.fouls, ps.fouls_drawn, ps.clean_sheets, ps.goals_conceded, ps.saves_total, ps.save_percentage, ps.penalties_saved, ps.created_at, ps.updated_at, ps.deleted_at,
    p.full_name,
    p.position,
    t.name as team_name,
    t.short_name as team_short_name
FROM player_statistics ps
JOIN players p ON ps.player_id = p.id AND p.deleted_at IS NULL
JOIN teams t ON p.team_id = t.id AND t.deleted_at IS NULL
WHERE ps.season = $1
  AND ps.competition = $2
  AND ps.deleted_at IS NULL
ORDER BY ps.goals DESC, ps.assists DESC
LIMIT $3
`

type GetTopScorersParams struct {
	Season      string `json:"season"`
	Competition string `json:"competition"`
	Limit       int32  `json:"limit"`
}

type GetTopScorersRow struct {
	ID              int32              `json:"id"`
	PlayerID        int32              `json:"player_id"`
	Season          string             `json:"season"`
	Competition     string             `json:"competition"`
	MatchesPlayed   int32              `json:"matches_played"`
	MatchesStarted  int32              `json:"matches_started"`
	MinutesPlayed   int32              `json:"minutes_played"`
	SubOn           int32              `json:"sub_on"`
	SubOff          int32              `json:"sub_off"`
	Goals           int32              `json:"goals"`
	Assists         int32              `json:"assists"`
	ShotsTotal      int32              `json:"shots_total"`
	ShotsOnTarget   int32              `json:"shots_on_target"`
	ShotAccuracy    pgtype.Numeric     `json:"shot_accuracy"`
	GoalConversion  pgtype.Numeric     `json:"goal_conversion"`
	PassesTotal     int32              `json:"passes_total"`
	PassesCompleted int32              `json:"passes_completed"`
	PassAccuracy    pgtype.Numeric     `json:"pass_accuracy"`
	KeyPasses       int32              `json:"key_passes"`
	Crosses         int32              `json:"crosses"`
	Tackles         int32              `json:"tackles"`
	TacklesWon      int32              `json:"tackles_won"`
	Interceptions   int32              `json:"interceptions"`
	Clearances      int32              `json:"clearances"`
	BlockedShots    int32              `json:"blocked_shots"`
	Duels           int32              `json:"duels"`
	DuelsWon        int32              `json:"duels_won"`
	AerialDuels     int32              `json:"aerial_duels"`
	AerialDuelsWon  int32              `json:"aerial_duels_won"`
	YellowCards     int32              `json:"yellow_cards"`
	RedCards        int32              `json:"red_cards"`
	Fouls           int32              `json:"fouls"`
	FoulsDrawn      int32              `json:"fouls_drawn"`
	CleanSheets     *int32             `json:"clean_sheets"`
	GoalsConceded   *int32             `json:"goals_conceded"`
	SavesTotal      *int32             `json:"saves_total"`
	SavePercentage  pgtype.Numeric     `json:"save_percentage"`
	PenaltiesSaved  *int32             `json:"penalties_saved"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	FullName        string             `json:"full_name"`
	Position        string             `json:"position"`
	TeamName        string             `json:"team_name"`
	TeamShortName   string             `json:"team_short_name"`
}

func (q *Queries) GetTopScorers(ctx context.Context, arg GetTopScorersParams) ([]GetTopScorersRow, error) {
	rows, err := q.db.Query(ctx, getTopScorers, arg.Season, arg.Competition, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopScorersRow{}
	for rows.Next() {
		var i GetTopScorersRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Season,
			&i.Competition,
			&i.MatchesPlayed,
			&i.MatchesStarted,
			&i.MinutesPlayed,
			&i.SubOn,
			&i.SubOff,
			&i.Goals,
			&i.Assists,
			&i.ShotsTotal,
			&i.ShotsOnTarget,
			&i.ShotAccuracy,
			&i.GoalConversion,
			&i.PassesTotal,
			&i.PassesCompleted,
			&i.PassAccuracy,
			&i.KeyPasses,
			&i.Crosses,
			&i.Tackles,
			&i.TacklesWon,
			&i.Interceptions,
			&i.Clearances,
			&i.BlockedShots,
			&i.Duels,
			&i.DuelsWon,
			&i.AerialDuels,
			&i.AerialDuelsWon,
			&i.YellowCards,
			&i.RedCards,
			&i.Fouls,
			&i.FoulsDrawn,
			&i.CleanSheets,
			&i.GoalsConceded,
			&i.SavesTotal,
			&i.SavePercentage,
			&i.PenaltiesSaved,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FullName,
			&i.Position,
			&i.TeamName,
			&i.TeamShortName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayerStats = `-- name: UpdatePlayerStats :one
UPDATE player_statistics
SET
    matches_played = $2,
    matches_started = $3,
    minutes_played = $4,
    sub_on = $5,
    sub_off = $6,
    goals = $7,
    assists = $8,
    shots_total = $9,
    shots_on_target = $10,
    shot_accuracy = $11,
    goal_conversion = $12,
    passes_total = $13,
    passes_completed = $14,
    pass_accuracy = $15,
    key_passes = $16,
    crosses = $17,
    tackles = $18,
    tackles_won = $19,
    interceptions = $20,
    clearances = $21,
    blocked_shots = $22,
    duels = $23,
    duels_won = $24,
    aerial_duels = $25,
    aerial_duels_won = $26,
    yellow_cards = $27,
    red_cards = $28,
    fouls = $29,
    fouls_drawn = $30
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, player_id, season, competition, matches_played, matches_started, minutes_played, sub_on, sub_off, goals, assists, shots_total, shots_on_target, shot_accuracy, goal_conversion, passes_total, passes_completed, pass_accuracy, key_passes, crosses, tackles, tackles_won, interceptions, clearances, blocked_shots, duels, duels_won, aerial_duels, aerial_duels_won, yellow_cards, red_cards, fouls, fouls_drawn, clean_sheets, goals_conceded, saves_total, save_percentage, penalties_saved, created_at, updated_at, deleted_at
`

type UpdatePlayerStatsParams struct {
	ID              int32          `json:"id"`
	MatchesPlayed   int32          `json:"matches_played"`
	MatchesStarted  int32          `json:"matches_started"`
	MinutesPlayed   int32          `json:"minutes_played"`
	SubOn           int32          `json:"sub_on"`
	SubOff          int32          `json:"sub_off"`
	Goals           int32          `json:"goals"`
	Assists         int32          `json:"assists"`
	ShotsTotal      int32          `json:"shots_total"`
	ShotsOnTarget   int32          `json:"shots_on_target"`
	ShotAccuracy    pgtype.Numeric `json:"shot_accuracy"`
	GoalConversion  pgtype.Numeric `json:"goal_conversion"`
	PassesTotal     int32          `json:"passes_total"`
	PassesCompleted int32          `json:"passes_completed"`
	PassAccuracy    pgtype.Numeric `json:"pass_accuracy"`
	KeyPasses       int32          `json:"key_passes"`
	Crosses         int32          `json:"crosses"`
	Tackles         int32          `json:"tackles"`
	TacklesWon      int32          `json:"tackles_won"`
	Interceptions   int32          `json:"interceptions"`
	Clearances      int32          `json:"clearances"`
	BlockedShots    int32          `json:"blocked_shots"`
	Duels           int32          `json:"duels"`
	DuelsWon        int32          `json:"duels_won"`
	AerialDuels     int32          `json:"aerial_duels"`
	AerialDuelsWon  int32          `json:"aerial_duels_won"`
	YellowCards     int32          `json:"yellow_cards"`
	RedCards        int32          `json:"red_cards"`
	Fouls           int32          `json:"fouls"`
	FoulsDrawn      int32          `json:"fouls_drawn"`
}

func (q *Queries) UpdatePlayerStats(ctx context.Context, arg UpdatePlayerStatsParams) (PlayerStatistic, error) {
	row := q.db.QueryRow(ctx, updatePlayerStats,
		arg.ID,
		arg.MatchesPlayed,
		arg.MatchesStarted,
		arg.MinutesPlayed,
		arg.SubOn,
		arg.SubOff,
		arg.Goals,
		arg.Assists,
		arg.ShotsTotal,
		arg.ShotsOnTarget,
		arg.ShotAccuracy,
		arg.GoalConversion,
		arg.PassesTotal,
		arg.PassesCompleted,
		arg.PassAccuracy,
		arg.KeyPasses,
		arg.Crosses,
		arg.Tackles,
		arg.TacklesWon,
		arg.Interceptions,
		arg.Clearances,
		arg.BlockedShots,
		arg.Duels,
		arg.DuelsWon,
		arg.AerialDuels,
		arg.AerialDuelsWon,
		arg.YellowCards,
		arg.RedCards,
		arg.Fouls,
		arg.FoulsDrawn,
	)
	var i PlayerStatistic
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Season,
		&i.Competition,
		&i.MatchesPlayed,
		&i.MatchesStarted,
		&i.MinutesPlayed,
		&i.SubOn,
		&i.SubOff,
		&i.Goals,
		&i.Assists,
		&i.ShotsTotal,
		&i.ShotsOnTarget,
		&i.ShotAccuracy,
		&i.GoalConversion,
		&i.PassesTotal,
		&i.PassesCompleted,
		&i.PassAccuracy,
		&i.KeyPasses,
		&i.Crosses,
		&i.Tackles,
		&i.TacklesWon,
		&i.Interceptions,
		&i.Clearances,
		&i.BlockedShots,
		&i.Duels,
		&i.DuelsWon,
		&i.AerialDuels,
		&i.AerialDuelsWon,
		&i.YellowCards,
		&i.RedCards,
		&i.Fouls,
		&i.FoulsDrawn,
		&i.CleanSheets,
		&i.GoalsConceded,
		&i.SavesTotal,
		&i.SavePercentage,
		&i.PenaltiesSaved,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTeamStats = `-- name: UpdateTeamStats :one
UPDATE team_statistics
SET
    matches_played = $2,
    wins = $3,
    draws = $4,
    losses = $5,
    points = $6,
    position = $7,
    goals_scored = $8,
    goals_conceded = $9,
    goal_difference = $10,
    clean_sheets = $11,
    goals_per_match = $12,
    home_wins = $13,
    home_draws = $14,
    home_losses = $15,
    away_wins = $16,
    away_draws = $17,
    away_losses = $18,
    possession = $19,
    pass_accuracy = $20,
    shots_per_match = $21,
    shots_on_target_percentage = $22,
    yellow_cards = $23,
    red_cards = $24,
    current_form = $25
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, team_id, season, competition, matches_played, wins, draws, losses, points, position, goals_scored, goals_conceded, goal_difference, clean_sheets, goals_per_match, home_wins, home_draws, home_losses, away_wins, away_draws, away_losses, possession, pass_accuracy, shots_per_match, shots_on_target_percentage, yellow_cards, red_cards, current_form, created_at, updated_at, deleted_at
`

type UpdateTeamStatsParams struct {
	ID                      int32          `json:"id"`
	MatchesPlayed           int32          `json:"matches_played"`
	Wins                    int32          `json:"wins"`
	Draws                   int32          `json:"draws"`
	Losses                  int32          `json:"losses"`
	Points                  int32          `json:"points"`
	Position                *int32         `json:"position"`
	GoalsScored             int32          `json:"goals_scored"`
	GoalsConceded           int32          `json:"goals_conceded"`
	GoalDifference          int32          `json:"goal_difference"`
	CleanSheets             int32          `json:"clean_sheets"`
	GoalsPerMatch           pgtype.Numeric `json:"goals_per_match"`
	HomeWins                int32          `json:"home_wins"`
	HomeDraws               int32          `json:"home_draws"`
	HomeLosses              int32          `json:"home_losses"`
	AwayWins                int32          `json:"away_wins"`
	AwayDraws               int32          `json:"away_draws"`
	AwayLosses              int32          `json:"away_losses"`
	Possession              pgtype.Numeric `json:"possession"`
	PassAccuracy            pgtype.Numeric `json:"pass_accuracy"`
	ShotsPerMatch           pgtype.Numeric `json:"shots_per_match"`
	ShotsOnTargetPercentage pgtype.Numeric `json:"shots_on_target_percentage"`
	YellowCards             int32          `json:"yellow_cards"`
	RedCards                int32          `json:"red_cards"`
	CurrentForm             *string        `json:"current_form"`
}

func (q *Queries) UpdateTeamStats(ctx context.Context, arg UpdateTeamStatsParams) (TeamStatistic, error) {
	row := q.db.QueryRow(ctx, updateTeamStats,
		arg.ID,
		arg.MatchesPlayed,
		arg.Wins,
		arg.Draws,
		arg.Losses,
		arg.Points,
		arg.Position,
		arg.GoalsScored,
		arg.GoalsConceded,
		arg.GoalDifference,
		arg.CleanSheets,
		arg.GoalsPerMatch,
		arg.HomeWins,
		arg.HomeDraws,
		arg.HomeLosses,
		arg.AwayWins,
		arg.AwayDraws,
		arg.AwayLosses,
		arg.Possession,
		arg.PassAccuracy,
		arg.ShotsPerMatch,
		arg.ShotsOnTargetPercentage,
		arg.YellowCards,
		arg.RedCards,
		arg.CurrentForm,
	)
	var i TeamStatistic
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Season,
		&i.Competition,
		&i.MatchesPlayed,
		&i.Wins,
		&i.Draws,
		&i.Losses,
		&i.Points,
		&i.Position,
		&i.GoalsScored,
		&i.GoalsConceded,
		&i.GoalDifference,
		&i.CleanSheets,
		&i.GoalsPerMatch,
		&i.HomeWins,
		&i.HomeDraws,
		&i.HomeLosses,
		&i.AwayWins,
		&i.AwayDraws,
		&i.AwayLosses,
		&i.Possession,
		&i.PassAccuracy,
		&i.ShotsPerMatch,
		&i.ShotsOnTargetPercentage,
		&i.YellowCards,
		&i.RedCards,
		&i.CurrentForm,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
