# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - gocritic
    - gosec
    - misspell
    - unconvert
    - unparam
    - whitespace
    - revive
    - gocyclo
    - gocognit
    - bodyclose
    - dupl
    - errorlint
    - exhaustive
    - copyloopvar
    - goconst
    - godot
    - mnd
    - goprintffuncname
    - nolintlint
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
  disable:
    - funlen
    - lll

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    settings:
      shadow:
        strict: true

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  goimports:
    local-prefixes: github.com/emiliospot/footie/api

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - commentedOutCode
      - whyNoLint

  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: false
        arguments:
          - ["ID", "URL", "API", "JWT", "DB", "UUID", "HTTP", "AWS", "S3"]

issues:
  exclude-dirs:
    - vendor
    - tmp
    - bin
  exclude-rules:
    - path: '_test\.go$'
      linters:
        - errcheck
        - gosec
        - dupl
        - goconst
        - revive
        - govet
        - whitespace
    - path: "^cmd/"
      linters:
        - mnd
        - govet
    - path: "^internal/config/"
      linters:
        - mnd
    - path: "^internal/infrastructure/"
      linters:
        - mnd
        - govet
    - path: "^internal/domain/models/"
      linters:
        - mnd
    - path: "^internal/api/middleware/"
      linters:
        - mnd
    - path: '^internal/api/router\.go$'
      linters:
        - mnd
    - path: "^internal/api/handlers/"
      linters:
        - govet
      text: 'shadow: declaration of "err"'
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
